<?php
$tituloPagina = "agil mindset | Termos de Uso";
$descricaoPagina = "Entenda os termos de uso na plataforma agilmindset.";
$urlPagina = "https://agilmindset.com/termos-de-uso.php";
$urlAmigavelPagina = "termos-de-uso";
?>
<?php require_once("./inc/head.php"); ?>

<body>
    <?php require_once("./inc/header.php"); ?>
    <main class="container-fluid px-0 politicas">
        <section class="container-fluid mx-0 p-2 p-sm-4 p-md-5">
            <article class="d-flex flex-wrap flex-md-nowrap align-items-center p-0">
                <img srcset="./assets/img/termos-de-uso-150x150.jpg 150w, ./assets/img/termos-de-uso-200x200.jpg 200w, ./assets/img/termos-de-uso-250x250.jpg 250w, ./assets/img/termos-de-uso-300x300.jpg 300w, ./assets/img/termos-de-uso-350x350.jpg 350w, ./assets/img/termos-de-uso-400x400.jpg 400w, ./assets/img/termos-de-uso-450x450.jpg 450w, ./assets/img/termos-de-uso-500x500.jpg 500w, ./assets/img/termos-de-uso-550x550.jpg 550w, ./assets/img/termos-de-uso-574x574.jpg 574w, ./assets/img/termos-de-uso-267x267.jpg 267w, ./assets/img/termos-de-uso-300x300.jpg 300w, ./assets/img/termos-de-uso-224x224.jpg 224w, ./assets/img/termos-de-uso-254x254.jpg 254w, ./assets/img/termos-de-uso-304x304.jpg 304w, ./assets/img/termos-de-uso-344x344.jpg 344w, ./assets/img/termos-de-uso-464x464.jpg 464w, ./assets/img/termos-de-uso-484x484.jpg 484w, ./assets/img/termos-de-uso-614x614.jpg 614w" sizes="(min-width: 2500px) 614px, (min-width: 2000px) 484px, (min-width: 1920px) 464px, (min-width: 1440px) 344px, (min-width: 1280px) 304px, (min-width: 1080px) 254px, (min-width: 960px) 224px, (min-width: 720px) 300px, (min-width: 640px) 267px, (min-width: 574px) 574px, (min-width: 550px) 550px, (min-width: 500px) 500px, (min-width: 450px) 450px, (min-width: 400px) 400px, (min-width: 350px) 350px, (min-width: 300px) 300px, (min-width: 250px) 250px, (min-width: 200px) 200px, 150px" src="./assets/img/termos-de-uso.jpg" class="col-12 col-sm-5 col-md-3 px-0 pl-md-0 pr-md-3 banner-img" alt="Termos de Uso - entenda quais são os termos e condições para o uso da plataforma agilmindset">
                <div class="col-12 col-sm-7 col-md-9 p-4">
                    <h1 class="">Termos<br /><span class="box">e Condições de Uso</span></h1>
                    <p class="mt-5">A <b>agilmindset</b> proporciona um ambiente digital de <b>compartilhamento, cocriação, de coexistência</b>. E para que surjam projetos inovadores e que agreguem valor aos negócios, é imprescindível a boa convivência entre todos os usuários. Para garantir essa <b>boa convivência</b>, elaboramos esses <b>Termos de Uso</b> (ou Termos e Condiçõe de Uso).</p>
                    <p>Se houver qualquer dúvida, conte conosco! Basta <a href="mailto:webmaster@agilmindset.com?subject=Mensagem%20enviada%20via%20site%20agilMindset" rel="noopener noreferrer" target="_blank" title="Enviar email para webmaster@agilmindset.com">entrar em contato</a> - teremos prazer em ajudar você!</p>
                    <p class="mb-5"><b>Lembre-se de que ao navegar no site, você está ciente e de acordo com nossas <a href="politicas-de-privacidade" target="_blank" rel="noopener noreferrer" title="Leia as políticas de privacidade da agilmindset">Políticas de Privacidade</a> e Termos de Uso.</b></p>
                </div>
            </article>
        </section>
        <section class="container-fluid mx-0 p-2 p-sm-4 p-md-5 bg-light">
            <article class="container">
                <section class="row my-3">
                    <header class="col-12 py-5 px-3 px-sm-4 px-md-5 bg-pink">
                        <h3 class="mb-3"><b>Aviso Importante</b></h3>
                        <p class="col-12 mt-3 mb-0">OS USUÁRIOS MENORES DE 18 ANOS DE IDADE SOMENTE PODERÃO EFETUAR O REGISTRO OU CADASTRO NESSE SITE SE DEVIDAMENTE REPRESENTADOS OU ASSISTIDOS POR SEUS REPRESENTANTES OU ASSISTENTES LEGAIS, DEVENDO ESSES SER RESPONSÁVEIS NA ESFERA CÍVEL POR TODO E QUALQUER ATO PRATICADO PELOS MENORES QUANDO DA UTILIZAÇÃO DO SITE, CONFORME PREVISTO NOS ARTIGOS <a href="https://www.jusbrasil.com.br/topicos/10620733/artigo-1634-da-lei-n-10406-de-10-de-janeiro-de-2002" target="_blank" rel="noopener noreferrer" title="Leia o artigo 1.634 do Código Civil">1.634</a> E <a href="https://www.jusbrasil.com.br/topicos/10615826/artigo-1690-da-lei-n-10406-de-10-de-janeiro-de-2002" target="_blank" rel="noopener noreferrer" title="Leia o artigo 1.690 do Código Civil">1.690</a> DO CÓDIGO CIVIL. OS REPRESENTANTES LEGAIS SERÃO RESPONSÁVEIS, POR TODO E QUALQUER ATO ILÍCITO PRATICADO PELOS MENORES QUANDO DA UTILIZAÇÃO DO SITE.</p>
                    </header>
                </section>
                <section class="row my-3">
                    <h2 class="col-12 mt-4">Termos Gerais</h2>
                    <article class="col-12 my-3">
                        <p class="col-12 mt-3">Esses Termos de Uso apresentam as Regras e Condições Gerais aplicáveis ao uso dos serviços oferecidos pela <b>agilmindset</b> - projeto idealizado e executado exclusivamente pela "Djament Comunicação", nome fantasia da empresa tipo MEI Marcelo Diament37484380873, inscrita no CNPJ sob n.º 20.196.856/0001-91, doravante denominada "<b>agilmindset</b>", o qual consiste em uma ferramenta digital - mais especificamente uma plataforma online - que otimiza processos de maneira dinâmica, interativa e colaborativa.</p>
                        <p class="col-12 mb-3">Ao navegar no site e/ou na plataforma <b>agilmindset</b>, o usuário está expressamente ciente e de acordo com os <b>Termos de Uso</b> (e suas condições e regras) bem como com as <a href="./politicas-de-privacidade" target="_blank" rel="noopener noreferrer" title="Leia as políticas de privacidade da agilmindset">Políticas de Privacidade</a> do site <b>agilmindset</b>. Sendo assim, o aceite é obrigatório e indispensável para utilização dos serviços oferecidos pela <b>agilmindset</b>, sejam eles pagos ou gratuitos, com ou sem acesso restrito.</p>
                    </article>
                </section>
                <section class="row my-3">
                    <h2 class="col-12 mt-4">Termos e Condições de Uso</h2>
                    <article class="col-12 my-3">
                        <p class="col-12 my-3">A Djament Comunicação ("<b>agilmindset</b>") tem como norte em cada uma de suas ações o respeito ao usuário - seja ele visitante, cliente, parceiro e/ou colaborador. Recomendamos fortemente a leitura de nossos termos. Ao navegar no site, você está ciente e de acordo com as regras de utilização, proteção e segurança aqui estabelecidas.</p>
                    </article>
                    <article class="col-12 my-3">
                        <h3 class="text-center mt-1 mb-4">Condições Gerais</h3>
                        <p class="col-12 mt-3">Ao optar pelo acesso à <b>agilmindset</b>, o visitante compreende, reconhece e concorda que sua utilização é regida pelo ordenamento jurídico da República Federativa do Brasil em relação à conduta online e conteúdo disponibilizado. O uso e/ou usufruto desse wrestringe-se ao privado, sendo vedada sua utilização comercial com fins lucrativos por terceiros não autorizados; assim como é proibido - e protegido por legislação competente - o uso de qualquer software ou sistema automatizado para extrair dados deste wpara a exibição em qualquer outro lugar do World Wide Web ("screen scraping") sem o consentimento expresso de seu(s) proprietário(s).</p>
                        <p class="col-12">A <b>agilmindset</b> fará de todo o possível para manter seu site no ar durante 24 (vinte e quatro) horas por dia sem interrupção, salvo a impossibilidade de funcionamento integral e ininterrupto do sistema de telecomunicação ou de informática, por eventos causados nos casos fortuitos ou de força maior; nesta situação de fragilidade também se incluindo, dado sua complexidade, a dependência de serviços de telecomunicações prestados por terceiros, razão também pela qual <b>não se garante, de forma alguma, a prestação do serviço de forma ininterrupta e/ou isenta de erros</b>.</p>
                        <p class="col-12">A <b>agilmindset</b> isenta-se da responsabilidade por qualquer erro e/ou atraso na remoção de conteúdo impreciso, ilícito ou censurável. A equipe da <b>agilmindset</b> pode mudar, a qualquer tempo e sem aviso prévio, o conteúdo e funcionalidades do website.</p>
                        <p class="col-12 mb-3">A <b>agilmindset</b> poderá, a qualquer tempo, alterar o presente instrumento - visando o aprimoramento, bem como a melhoria dos serviços prestados. O novo instrumento contratual entrará em vigor sem prejuízo dos produtos veiculados na vigência do contrato anterior. Assim, a <b>agilmindset</b> recomenda ao usuário que tenha o costume de reler atentamente os termos e condições de uso sempre que acessar o site ou realizar qualquer operação por meio desse - assim como recomenda que seja feita a releitura das <a href="politicas-de-privacidade" target="_blank" rel="noopener noreferrer" title="Leia as políticas de privacidade da agilmindset">Políticas de Privacidade</a>.</p>
                        <p class="col-12">A <b>agilmindset</b> não se responsabiliza por qualquer dano, prejuízo e/ou perda no equipamento do usuário que seja causado por falhas no sistema, no servidor ou na internet decorrentes de condutas de terceiros, ressalvado que eventualmente, o sistema poderá não estar disponível por motivos técnicos e/ou falhas da internet ou por qualquer outro evento fortuito ou de força maior alheio ao seu controle.</p>
                        <p class="col-12">Nenhuma garantia de qualquer tipo, implícita ou explícita, incluindo, sem limitação, qualquer garantia de propriedade, não violação de direitos de terceiros, comerciabilidade, qualidade satisfatória, adequação a um fim específico e ausência de vírus de computador é apresentada com relação a este Site e/ou aos dados transmitidas por meio do site.</p>
                        <p class="col-12">O usuário reconhece e aceita que (a) o estágio atual da técnica não permite a elaboração de programas de computador totalmente isentos de vícios ou defeitos e que, assim sendo, a <b>agilmindset</b> não pode garantir que o site operará ininterruptamente ou livre de vícios, vírus ou defeitos; e (b) o site não foi desenvolvido sob encomenda do usuário, mas para uso genérico, razão pela qual a <b>agilmindset</b> não pode garantir que este atenderá quaisquer necessidades específicas do usuário.</p>
                        <p class="col-12 mb-3">Quando no site existirem "links" para outros sites, a <b>agilmindset</b> recomenda ao usuário consultar as respectivas "Políticas de Privacidade" e "Termos de Uso" de tais sites, bem como quaisquer outros regulamentos específicos de cada um deles, caso acesse-os. A <b>agilmindset</b> não presta aval nem garante ou representa quaisquer terceiros cujos links constem do site, sendo certo que sua disponibilização no site visa exclusivamente proporcionar maior comodidade e opções de entretenimento ao usuário. O usuário reconhece que todo e qualquer problema gerado em tais sites deve ser resolvido com a empresa titular do respectivo site, sem a participação - direta nem indireta - da <b>agilmindset</b>.</p>
                    </article>
                    <article class="col-12 my-3">
                        <h3 class="text-center mt-1 mb-4">Confidencialidade</h3>
                        <p class="col-12 mt-3">A <b>agilmindset</b> tomará as medidas cabíveis para manter a confidencialidade, segurança e sigilo referentes a informações de usuários, porém não responderá por prejuízo que possa ser derivado da violação dessas medidas por parte de terceiros que utilizem as redes públicas ou a internet, subvertendo os sistemas de segurança para acessar as informações de um ou mais usuários. Ademais, <b>é de inteira responsabilidade do usuário o conteúdo por ele publicado e/ou compartilhado - cabendo ao mesmo manter o bom senso, o respeito aos demais usuários e a boa convivência</b>.</p>
                        <p class="col-12">Preocupada com a segurança e privacidade dos dados que trafegam no site, a <b>agilmindset</b> declara que a senha de acesso e demais dados que o usuário digitar na página do site são totalmente <b>protegidos por tecnologia de criptografia, com chave de segurança e transmissão dos dados através do certificado de segurança SSL (Secure Global Sign)</b>.</p>
                        <p class="col-12"><b>A agilmindset recomenda que o usuário nunca forneça sua senha a terceiros, utilize senhas fortes (com caracteres alfanuméricos e carcateres especiais, incluindo letras minúsculas e maiúsculas) e que troque a senha de acesso com certa frequência</b> (de preferência mensalmente).</p>
                        <p class="col-12 mb-3">A <b>agilmindset</b> se compromete a não ceder ou comercializar, sob nenhuma forma, informações individuais do usuário cadastrado sem a sua expressa autorização. O usuário é integralmente responsável pelo sigilo e utilização de sua senha e identidade - bem como por toda e qualquer declaração publicada na plaraforma e/ou site <b>agilmindset</b>.</p>
                    </article>
                    <article class="col-12 my-3">
                        <h3 class="text-center mt-1 mb-4">Sobre a Propriedade Intelectual</h3>
                        <p class="col-12 mt-3">O usuário acorda que o site, assim como os logotipos, marcas, insígnias, fotos, imagens, descrições, textos, layout, símbolos, sinais distintivos, manual(ais) e quaisquer outros materiais correlatos ao site, constituem, conforme o caso, direitos autorais, segredos de negócio e/ou direitos de propriedade da <b>agilmindset</b> ou seus licenciadores, conforme o caso, sendo tais direitos protegidos pela legislação nacional e internacional aplicável à propriedade intelectual, especialmente quanto aos termos e condições das Leis nºs <a href="https://www2.camara.leg.br/legin/fed/lei/1996/lei-9279-14-maio-1996-374644-norma-pl.html" target="_blank" rel="noopener noreferrer" title="Leia a Lei 9.279/96">9.279/96</a>, <a href="https://presrepublica.jusbrasil.com.br/legislacao/109879/lei-do-software-lei-9609-98" target="_blank" rel="noopener noreferrer" title="Leia a Lei 9.609/98">9.609/98</a> e <a href="https://presrepublica.jusbrasil.com.br/legislacao/92175/lei-de-direitos-autorais-lei-9610-98" target="_blank" rel="noopener noreferrer" title="Leia a Lei 9.610/98">9.610/98</a> e que não pleitearão ou reclamarão, a qualquer tempo, tais direitos de propriedade como se seus fossem.</p>
                        <p class="col-12">É expressamente proibido ao usuário a reprodução, a distribuição, a modificação, a exibição, a criação de trabalhos derivados ou qualquer outra forma de utilização do conteúdo deste site e dos materiais veiculados no ou pelo site.</p>
                        <p class="col-12"><b>Em atenção à proteção aos direitos do usuário, fica desde já esclarecido e acordado que ideias ou sugestões relacionadas a produtos, serviços ou quaisquer outros planos de trabalho, exceto quando expressamente requisitado pela agilmindset e acordado por escrito com assinatura e firma reconhecida de toas as partes envolvidas. Conforme legislação vigente, as ideias ou concepções abstratas, planos e esquemas não são protegidos no Brasil.</b></p>
                        <p class="col-12 mb-3">Deste modo, o usuário declara, reconhece e aceita que qualquer transmissão de ideias ou concepções poderá ser utilizada por quaisquer terceiros, inclusive pela <b>agilmindset</b>, para o propósito de desenvolvimento e/ou criação de produtos e/ou serviços utilizando tais informações, sem que gere qualquer obrigação de compensar o usuário.</p>
                    </article>
                </section>
                <section class="row my-3">
                    <h2 class="col-12 mt-4">Cadastro de Usuários</h2>
                    <article class="col-12 my-3">
                        <p class="col-12 mt-3">O cadastro do usuário deverá ser feito previamente pelo gestor do cliente adquirente da plataforma e será confirmado após o correto e completo preenchimento de todos os dados solicitados - com exceção da plataforma de demonstração (versão demo), que permitirá o cadastro feito pelo próprio usuário. Caberá ao usuário alterar sua senha pré definida após a confirmação de seu cadastro.</p>
                        <p class="col-12">Não será permitido ao usuário que se cadastre por mais de uma vez - caso isso venha a ocorrer, a <b>agilmindset</b> desabilitará, automaticamente, após verificação dos dados, definitivamente todos os cadastros deste usuário.</p>
                        <p class="col-12">Todo e qualquer usuário/visitante com idade menor que 18 anos deverá obter o consentimento expresso de seus pais ou representantes legais antes de fornecer os seus endereços de e-mail ou quaisquer dados à <b>agilmindset</b> por meio desse site ou <a href="mailto:webmaster@agilmindset.com?subject=Site%20agilMindset%20-%20Autorização%20de%20acesso%20de%20usuário%20com%20menos%20de%2018%20anos" rel="noopener noreferrer" target="_blank" title="Enviar email para webmaster@agilmindset.com com autorização de acesso por menor de 18 anos">por email</a>.</p>
                        <p class="col-12">Todas as informações fornecidas pelo usuário devem ser exatas, precisas, verdadeiras e devidamente atualizadas - caso ocorra qualquer alteração; reconhecendo o usuário, ainda, que a <b>agilmindset</b> não tem a obrigação de verificar a precisão dos dados transmitidos pelo usuário ou qualquer outra pessoa.</p>
                        <p class="col-12">Diante disso, a <b>agilmindset</b> não se responsabiliza pela correção de dados pessoais inseridos pelo usuário, sendo certo que o usuário – ou seus pais ou representantes legais, quando for o caso – garante e responde, em qualquer caso, pela veracidade, precisão e autenticidade dos dados pessoais cadastrados.</p>
                        <p class="col-12">O usuário concorda e está de acordo que a Internet, enquanto rede mundial de computadores à qual qualquer pessoa pode ter acesso, não é um meio totalmente seguro. No caso de utilização do site, a <b>agilmindset</b> não se responsabiliza em hipótese alguma por prejuízos de qualquer espécie, inclusive, mas sem limitação, àqueles decorrentes do uso de tais dados por terceiros ou extravio de dados do usuário cadastrado, decorrentes direta ou indiretamente do seu acesso ou navegação no site. Entretanto, a <b>agilmindset</b> assegura que dispõe de recursos técnicos que visam evitar ou atenuar os riscos inerentes da Internet, tais como o certificado de segurança SSL e a criptografia de senhas.</p>
                        <p class="col-12">A <b>agilmindset</b>, a seu critério exclusivo e absoluto, pode alterar os critérios de qualificação e/ou exigências para a manutenção de cadastrados no site. Deste modo, a <b>agilmindset</b> poderá imediatamente encerrar um ou mais registros do site, podendo externar posteriormente a justificativa ou motivos.</p>
                        <p class="col-12 mb-3">Fica ressalvado o direito do usuário em retificar quaisquer dados enviados à <b>agilmindset</b>. Entretanto, o direito de retificação do usuário não obstará ou substituirá o direito da <b>agilmindset</b> em pleitear as indenizações cabíveis, no caso de informações errôneas ensejarem quaisquer danos e/ou prejuízos à <b>agilmindset</b> ou a terceiros no período anterior à sua retificação pelo usuário - entendendo-se como tal o momento do efetivo recebimento de tal retificação pela <b>agilmindset</b>.</p>
                    </article>
                </section>
                <section class="row my-3">
                    <h2 class="col-12 mt-4">Sobre as Sanções</h2>
                    <article class="col-12 my-3">
                        <p class="col-12 mt-3">Sem prejuízo de outras medidas, a <b>agilmindset</b> poderá advertir, cancelar, suspender - temporária ou definitivamente - a conta do usuário a qualquer tempo e iniciar as ações cabíveis, se o usuário não cumprir qualquer dispositivo deste Termo de Uso, se descumprir com seus deveres de usuário, se não puder ser confirmada e verificada a identidade do usuário ou se qualquer informação fornecida por ele esteja incorreta ou se verificar que os anúncios ou qualquer atitude do usuário tenha causado algum dano a terceiros ou à própria <b>agilmindset</b> ou tenham a potencialidade de assim o fazer.</p>
                        <p class="col-12 mb-3">Caso o Usuário tenha seu cadastro inabilitado, todas as aquisições de produtos e/ou serviços adquiridos serão automaticamente cancelados. Para dirimir qualquer dúvida, a <b>agilmindset</b> poderá, a qualquer tempo, a seu exclusivo critério, solicitar o envio de documentação pessoal do usuário.</p>
                    </article>
                </section>
                <section class="row my-3">
                    <h2 class="col-12 mt-4">Disposições Finais</h2>
                    <article class="col-12 my-3">
                        <p class="col-12 mt-3">Determinados atos, incluindo, mas não limitado, a usos com propósitos ilegais, corrupção de informações ou dados, violação de direitos de propriedade industrial ou autoral, violação de direitos de terceiros (inclusive crianças), envio de mensagens de cunho ameaçador, racista, homofóbico, preconceituoso, intimidador, desrespeitoso ou pornográfico, interferir ou interromper o serviço prestado pelo site e/ou qualquer tentativa de propagação de vírus ou programa não desejado, poderão imediatamente resultar no encerramento de qualquer relação entre a <b>agilmindset</b> e o usuário, sendo o mesmo (o usuário) exclusivamente responsável por toda e qualquer ação e manifestação por parte dele.</p>
                        <p class="col-12">Caso reste qualquer dúvida a respeito do conteúdo do presente instrumento, por favor, contate a "Djament Comunicação", nome fantasia da empresa tipo MEI Marcelo Diament37484380873, inscrita no CNPJ sob n.º 20.196.856/0001-91, através do email <a href="mailto:webmaster@agilmindset.com?subject=Mensagem%20enviada%20via%20site%20agilMindset%20Dúvida%20sobre%20Termos%20de%20Uso&body=Gostaria%20que%20esclarecessem%20a%20seguinte%20dúvida%20sobre%os%20Termos%20de%20Uso%20do%20site" rel="noopener noreferrer" target="_blank" title="Enviar email para webmaster@agilmindset.com sobre os Termos de Uso">webmaster [@] agilmindset [.] com</a>.</p>
                        <p class="col-12">Caso qualquer cláusula, termo ou disposição deste contrato seja declarada nula, tal nulidade não afetará quaisquer outras cláusulas, termos ou disposições aqui contidas, as quais deverão permanecer em pleno vigor e efeito. A tolerância por qualquer uma das partes com relação a qualquer violação do presente contrato ou sua omissão no exercício de qualquer direito outorgado pelo mesmo, não será considerado como novação ou renúncia em relação a qualquer violação futura, seja semelhante ou não, ou ao exercício por qualquer uma das partes de qualquer direito futuro conferido por este instrumento.</p>
                        <p class="col-12">Este contrato supera quaisquer acordos, verbais ou escritos, anteriormente mantidos entre as partes, especialmente com relação ao uso do site pelo usuário. Caso surja qualquer desavença que não seja resolvida amigavelmente entre as partes, as mesmas se comprometem em submeter tal desavença a um mediador independente, com conhecimento técnico da matéria, que terá a função exclusiva de esclarecer e mediar o ponto divergente, a fim de que as partes alcancem um acordo, colocando fim à desavença. Caso as partes não alcancem um acordo no prazo máximo de 30 dias corridos sobre qualquer desavença e/ou disputa oriunda deste Contrato, as partes contratantes elegem o foro da Comarca da Capital do Estado de São Paulo, com renúncia expressa de qualquer outro, por mais privilegiado que seja, sendo aplicadas as leis brasileiras para dirimir quaisquer questões ou litígios oriundos do presente contrato.</p>
                        <p class="col-12">O usuário, ou, se for o caso, seu pai/mãe ou representante legal, reconhece expressamente ter lido, analisado e aceito integralmente as condições acima estabelecidas, comprometendo-se cumpri-las integralmente.</p>
                        <p class="col-12 my-4 text-center">&copy; Copyright 2019 - <?php echo date("Y"); ?> | <a id="djamentCopyright" href="https://djament.com.br" title="Acesse o site da Djament Comunicação, idealizadora desse projeto" target="_blank" rel="noopener noreferrer">Djament</a> - Todos os direitos reservados</p>
                    </article>
                </section>
            </article>
        </section>
        <?php require_once("./inc/banner-secundario.php"); ?>
    </main>
    <?php require_once("./inc/footer.php"); ?>
</body>

</html>